apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-shop-deployment
spec:
  selector:
    matchLabels:
      app: coffee-shop-deployment
  template:
    metadata:
      labels:
        app: coffee-shop-deployment
    spec:
      containers:
      - name: coffee-shop-deployment
        image: mohsinkhan2220/my-coffee-shop:v3
        resources:
          limits:
            memory: "600Mi"
            cpu: "900m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: coffee-shop-svc
spec:
  selector:
    app: coffee-shop-deployment
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32767
  type: NodePort

